//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBL_TRN_TASKS_CLASSLIBRARY
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TRN_USER
    {
        public int USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_ADDRESS { get; set; }
        public string USER_CITY { get; set; }
    }
}
